version: '3'
services: 
  node_app: 
    container_name: node_app
    restart: always
    build: .
    ports:
      - '3001:3001'
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo
    command: mongod --port 27017
    ports: 
      - '27018:27017'
    volumes:
      - './data/db:/data/db'
      